### ISSUE TITLE
Little documentation issue

### ISSUE THREAD

**Issue by benbender** [mandango/mandango#1]
Hey there, 

there is a little issue on the mandango-homepage. If you go to http://mandango.org and click on Documentation the link is ok.
If you are on http://mandango.org/doc/ the link "Documentation" in the top-nav-bar points to http://mandango.org/documentation/ instead of http://mandango.org/doc/. 

A little fix would be nice :)

**Comment by pablodip** [comment]
Fixed, thanks! I don't know why I didn't receive a notification from this issue :S
