### ISSUE TITLE
cache processing is self overwriting (and crash...)

### ISSUE THREAD

**Issue by brikou** [mandango/mandango#13]
the cache is maybe not reliable, I've made some test with ab command (apache bench) with maybe concurent level set to 10 or more and sometimes, the resulting cache make the application crash... with an error about scalar variable. In order to solve it I have to empty the cache folder...

Maybe it would be more reliable to use zend cache... ?

**Comment by pablodip** [comment]
Could you say more information about the tests? Or even better to show the code, please?

It must be a bug in the fileystem implementation of the CacheInterface. What we should probably do is to add more common implementations.

I don't like Zend Cache because it depends on another Zend libraries and it doesn't have an independent git repository (and the zf2 one is huge).

**Comment by brikou** [comment]
I relauch ab a few time to have this error again... and I got it

here is the md5.php file corresponding to the bug

``` php

<?php

return 1;ray (
  'fields' => 
  array (
    'affiche' => 1,
  ),
);
```

It looks like a mixture between 2 caching files : maybe...

1st one:

``` php

<?php

return 1;
```

2nd one:

``` php

<?php

return array (
  'fields' => 
  array (
    'affiche' => 1,
  ),
);
```

I think that the generated filename of cache file is not unique (or not enough on high conccurency)...

Tell me what you think of this issue ;)

thx

**Comment by brikou** [comment]
in FilesystemCache.php (line 68) maybe add LOCK_EX flag to the file_put_contents

before:

``` php
<?php

        if (false === @file_put_contents($file, $content)) {
            throw new \RuntimeException(sprintf('Unable to write the "%s" file.', $file));
        }
```

after:

``` php
<?php

        if (false === @file_put_contents($file, $content, LOCK_EX)) {
            throw new \RuntimeException(sprintf('Unable to write the "%s" file.', $file));
        }
```

maybe?

**Comment by brikou** [comment]
@pablodip just made a PR, (it seems to work on my few tests) https://github.com/mandango/mandango/pull/14

**Comment by pablodip** [comment]
I've just merged your PR. Anyway I'd like to provide more cache options, but not to depend on the huge (and sometimes coupled) zend. Do you have any idea?

**Comment by pablodip** [comment]
Bump
