### ISSUE TITLE
Mandango not compatible with PHP Mongo driver >= 1.2.7

### ISSUE THREAD

**Issue by sampart** [mandango/mandango#17]
[ErrorException]  
Runtime Notice: Declaration of Mandango\Logger\LoggableMongoCollection::batchInsert() should be compatible with that of MongoCollection::batchInsert() in /vagrant/vendor/mandango/src/Mandango/Logger/LoggableMongoCollection.php line 340

**Comment by johnwards** [comment]
@pablodip What are the chances of this getting a fix? ;)

**Comment by pablodip** [comment]
Hmm, tests are passing for me with the version 1.2.9. Could you please provide some more info to reproduce it?

**Comment by johnwards** [comment]
Is your test environment running in strict mode? This is a notice being fired when running PHP in strict mode I believe. It does it in FoodRisc on the vagrant server if you want to check. Just fire up vagrant and try and load the fixtures.

**Comment by pablodip** [comment]
Right, I see the notice now. Anyway, what's the difference of the new batchInsert method?

http://www.php.net/manual/en/mongocollection.batchinsert.php

**Comment by johnwards** [comment]
Hmm very odd. I don't know anything about php internals, so trying to read the C is a bit hard.

The collection code for batch insert changed its paramaters in this version:
https://github.com/mongodb/mongo-php-driver/blob/e62c3c659063cab4daca1c5b774bd62dccea7467/collection.c

But I might be completely barking up the wrong tree.

I wonder if @derickr would be able to explain this one?

**Comment by pablodip** [comment]
That commit is from 10 months ago, the last working version (1.2.6) is newer.

**Comment by johnwards** [comment]
Yeah I know, but I can't see any other changes to that method which are more recent. But I don't understand PHP internal stuff so I might be miss reading the lot of it.

**Comment by johnwards** [comment]
Is there anyway of diffing 1.2.6 and 1.2.7 to see what change caused this?

**Comment by derickr** [comment]
We added argument information in that release, so it now basically sets a require and a non-required argument. What's that line 340 like?

**Comment by pablodip** [comment]
https://github.com/mandango/mandango/blob/master/src/Mandango/Logger/LoggableMongoCollection.php#L63

**Comment by derickr** [comment]
Hmm, this could be a bug in the driver. Would you mind filing an issue at http://jira.mongodb.org so that I have it in my to-check queue?

**Comment by pablodip** [comment]
Done: https://jira.mongodb.org/browse/PHP-373

**Comment by pablodip** [comment]
@derickr Any chance of fixing this?

**Comment by derickr** [comment]
Yeah, I do want to have a look at this. But there are other pressing issues that have to be done first.
