### ISSUE TITLE
resetGroups/remove on persisted EmbedsMany documents

### ISSUE THREAD

**Issue by benfoxall** [mandango/mandango#21]
Using `->resetGroups()` on an EmbedsMany document doesn't seem to work for me when I've brought an object in from mongo. (prior to saving - it does remove the documents)

This also seems to be the case with `->remove[Embedded](…)`.

Would these rely on the object having an `_id`?

**Comment by pablodip** [comment]
Hmm, could you write an example, please?

**Comment by pablodip** [comment]
Bump.

**Comment by pablodip** [comment]
Bump.
