### ISSUE TITLE
Increasing number of connections on long lived scripts

### ISSUE THREAD

**Issue by benfoxall** [mandango/mandango#22]
When we run a fairly large test suite - the number of connections to mongo seems to keep on increasing until it maxes out and our tests start failing.  Is there perhaps a way of resetting the connections on tearDown?  Or it not to happen in the first place?

@pablodip - I think @johnwards asked you about it and you said it was purposeful, could you explain if so?

**Comment by pablodip** [comment]
Do you mean with Symfony2?

**Comment by benfoxall** [comment]
Yup, it's with Symfony2

**Comment by pablodip** [comment]
Sorry for the soo late reply. Do you still have issues with this?

**Comment by benfoxall** [comment]
I've not touched it in a while,  though @peterjwest might know?

**Comment by pablodip** [comment]
Bump.
