### ISSUE TITLE
Change generated code to user $this->getMandango()->create({{class}});

### ISSUE THREAD

**Issue by florynth** [mandango/mandango#24]
To allow better extension and unit testing any document creation should use the create method of Mandango instead of a direct new.

Exemple:

$embedded = new {{ embedded_one.class }}($this->getMandango());

Should be replace by

$embedded =  $this->getMandango()->create({{ embedded_one.class }});

**Comment by pablodip** [comment]
Where exactly?

**Comment by florynth** [comment]
In DocumentSetDocumentData.php.twig

Forgot to escape the {{ you can look for

$embedded = new {{ embedded_one.class }}($this->getMandango());

and replace by

$embedded = $this->getMandango()->create({{ embedded_one.class }});
