### ISSUE TITLE
Active, or inactive?.... That is the question!

### ISSUE THREAD

**Issue by j** [mandango/mandango#26]
Is this project active / inactive?  We've been using / contributing to ODM for about 8 months now and are interested in exploring other options.  I see that the last commit was 3 months ago.. Is it just b/c it's super awesome and stable, or no one is maintaining it! :P... If it's awesome and stable, I'd love to have some team members start using and contributing as well.

**Comment by j** [comment]
PS.  Will you be at the symfony SF live event?  If so, lets meet up!

**Comment by anasser** [comment]
I might like to contribute.

**Comment by mcuadros** [comment]
I am interested on contribute too we are devoloping a big project with Mandango and we forked it with some fixes, but will be great if the ppl keep alive this interesting project.

Regards

**Comment by zergin** [comment]
@mcuadros So did we. Does anyone have any news on this?

**Comment by mcuadros** [comment]
now one, i wrote a mail to Pablo without any response.

**Comment by florynth** [comment]
I already wrote him twice (the first time more than three months ago) to be a commiter on the project since we are using it at my job (I've done a sharding extension) and he never answered. Will wait more and maybe we should do a official fork and use this one ? Anyway will wait if he answer...

**Comment by j** [comment]
http://github.com/doctrine/mongodb-odm is active

**Comment by mcuadros** [comment]
I think that make the official fork is the best way if he dont answer in a while

@j ?¿? i dont want use doctrine.

**Comment by florynth** [comment]
I've done test of 5 library/odm 1 year ago and the 2 that should be use is Doctrine or Mandango. Since I don't like doctrine (really slow and a lot of handwork to do) mandango is, at my opinion, the best one to use

**Comment by mcuadros** [comment]
Hi,

Mongo is growing very fast and mandango is starting to be outdated, one good case is aggregation framework. or improve the mapreduce implementation. And many other improves possibles.

Some one is interesting, on make a official fork and make a core team? 

Regards

**Comment by j** [comment]
Granted it is "slow" to you guys, all ODMs are "slow".  I wouldn't really look at the speed of the application and instead look into how supported it is, stable it is, the test coverage, and that the library is moving in a forward progress, and not to mention, how many more developers use it.  I started to use Mandango, and have instead gave up on it because after looking at the core, it was kind of messy... so I've ended up forking Doctrine's MongoODM and already merged in a few of my PRs.  Since mongo is growing, more people are using it and contributing.  It was finally tagged.  From here, it will only get better.  Instead of looking into a dead project, look into contributing to an active project.

And back to the speed of Doctrine ODM: you should really look into another caching solution if speed is an issue.  Typically, on read intensive applications, I try to never let a client hit PHP at all.  And as far as a real-case scenario, we're using MongoDB ODM (without caching at all) on one of our applications and are serving a few million page views per day on only two app servers on Symfony2 (and it's a completely dynamic site.. some pages even get 60 queries that map to doctrine objects)... _barf_... Just making a point to say that it really isn't all that "slow".

Not to mention, doctrine as a community is starting to take over ODM mapping for most databases.  They just picked up OrientDB (https://github.com/doctrine/orientdb-odm).  OrientDB themselves started doing their own mapping and just ended up giving it to doctrine for their better community support.

Anyway, I'm a believer in choosing the best supported software.

:P

Hell, I'm the one who started this thread, haha!

**Comment by zergin** [comment]
@mcuadros I guess I would. Mandango lightness is still a selling point for me. But the project has to be picked up quickly or as said above it will soon become very outdated.

**Comment by thekarel** [comment]
@mcuadros I'd be glad to contrubute.

**Comment by anasser** [comment]
So how do we start? By fixing the reported issues first? or suggesting features then prioritizing?

**Comment by florynth** [comment]
Someone should do a "official fork" of the project. 
Define mission of the project (objective is to keep it light weight, do we put all behavior in the trunk or we do separate project for those, etc.)
Define roles for official contributors
Define our rules for development (unit test coverage, commit/pull request, documentation, how do we prioritize/assign issue, etc.) 
Create issue (bug, feature)
...

First thing first we should do a official fork and start conversation in the fork. I would have done it but I'm overbooked until June so I might slow down the project at first if I'm the central point...

What do you think ?

**Comment by mcuadros** [comment]
Our company is interested on take part on that but not on lead, we really dont have time for that, alteast now.

Any one is interested on lead it?

**Comment by zergin** [comment]
@mcuadros So would we. Unfortunately taking lead is very time consuming and I can't do it neither privately nor at company time. We do extend mandango on our own though and would like to take active part in getting this changes back to the community; shaping new ones likewise.

**Comment by anasser** [comment]
What does it take to be the lead?

**Comment by zergin** [comment]
@anasser I guess mostly initiative and some time to define short/long term goals and keeping it all together; but most of all responsibility not to leave the project behind after initial hype is over.

**Comment by rusnak** [comment]
@mcuadros I'd like to contribute too.

**Comment by thekarel** [comment]
Seems like @pablodip is back, there's an update after 6 months!
sha: a0c8f472fc9b2a4fb28696b7ed57fc39ca9bd24a

**Comment by pablodip** [comment]
Sorry for the late reply. We're talking this here: https://github.com/anasser/mandango/issues/1 so I close this issue.

**Comment by mcuadros** [comment]
Hi too all, 

At the end of this month we will start to use Mandango at production, so we are fixing some important bugs and making some performance enhancement. Too is merged the main fixes committed to the project in the last months and some others from other branches. (We are very interested on the dbrefs implementation from @zergin fork)

You can find our milestones at:
https://github.com/yunait/mandango/issues/milestones

And the list of the implemented issues at:
https://github.com/yunait/mandango/issues?state=closed

At the end of the 1.2 milestone we will make a official fork and rename it with a new name. So everyone is welcome to join to the new project. 

Our main objective is make mandango 2.4 complaint and make it production ready 

Regards to all 
PD.: @pablodip  thanks for your excellent job.

**Comment by ijy** [comment]
So, is this project still alive? I see the [other conversation](https://github.com/anasser/mandango/issues/1) breathed a little bit of life into the project for a short time but there's been activity in over a year and the [Google Group](https://groups.google.com/forum/#!forum/mandango-devs) has been dead for even longer.
