### ISSUE TITLE
save() has no effect when using setDocumentData()

### ISSUE THREAD

**Issue by rkyoku** [mandango/mandango#47]
Hi,

When I call save() after calling setDocumentData() (even with the "true" second parameter, although the cleaning seems to be forced in the generated code : "true || $bClean"), it has no effect and the values are _not_ saved. However, $doc->toArray(true) gives me the updated values. But they are not stored in the database.

In order to properly store the values, I have to manually call each (needed) setter before calling save().

// Does _not_ work
$oDoc->setDocumentData($aPostData);
$oDoc->save();

// Does work
$oDoc->setField1($mValue1);
$oDoc->save();

Thank you,

**Comment by pablodip** [comment]
Why do you use setDocumentData? It's an internal method. You should use
fromArray.

**Comment by rkyoku** [comment]
I'm sorry, I did not find any API explaining that. Either there is no API,
or it is not clearly visible.
If setDocumentData is internal, why make it public then?
Could you please point me to documentation indicating what to do in this
situation?

Thank you Pablo,

2013/3/13 Pablo Díez notifications@github.com

> Why do you use setDocumentData? It's an internal method. You should use
> fromArray.
>

**Comment by pablodip** [comment]
setDocumentData is for putting the data of the database in the documents.
The method public because it's called from outside, but it's an internal
method.

You should use fromArray.

**Comment by rkyoku** [comment]
Ok thank you Pablo. But is there an API somewhere, where all of that is
explained ? Because unless I'm mistaken, I could not find that information
in the docs that I found.

2013/3/13 Pablo Díez notifications@github.com

> setDocumentData is for putting the data of the database in the documents.
> The method public because it's called from outside, but it's an internal
> method.
> 
> You should use fromArray.
>

**Comment by pablodip** [comment]
No, there isn't. There only documentation that exists is what you can see
on mandango.org. I'll try to update it soon. Anyway, like always, the best
way to see how something works is not the documentation, but the code! ;)

**Comment by rkyoku** [comment]
Hi,

Thanks for the answer. Yes, that's how I found about the "setDocumentData"
:)

Congratulations for that superb lib anyway, I may seem noob but I'm
sensitive to the effort you provide. Keep it up!

Thanks again, see you soon Pablo!

Best regards,

Renaud
