### ISSUE TITLE
I want use combination $unset/$pull instead of $unset

### ISSUE THREAD

**Issue by scarkoo** [mandango/mandango#8]
Would you check this, please?

effective on embeddedsMany...

Core.php:2500

// updates
        foreach (\$updates as \$document) {
            if (\$document->isModified()) {
                $preUpdate\$query = \$document->queryForSave();
                \$collection->update(array('_id' => \$document->getId()), \$query, \$updateOptions);
                if (isset(\$query['\$unset'])) {
                    \$pullQuery = array('\$pull' => array());
                    foreach (\$query['\$unset'] as \$key => \$value) {
                        \$pullQuery['\$pull'][substr(\$key, 0, strrpos(\$key, '.'))] = null;
                    }
                    \$collection->update(array('_id' => \$document->getId()), \$pullQuery);
                }
                \$document->clearModified();$resetGroupsCode$postUpdate
            }
        }

**Comment by pablodip** [comment]
Why do you want to use this?
