### ISSUE TITLE
Method ::setDocumentData() is always clear the default values

### ISSUE THREAD

**Issue by Horzerus** [mandango/mandango#9]
If the model has fields with default values then the method ::setDocumentData() in the base class is always clear the default values.
## Base model class code:

```
public function initializeDefaults()
{
    $this->setCount(0);
}
.....
public function setDocumentData($data, $clean = false)
{
    if (true || $clean) {  // <---- !?
        $this->data = array();
        $this->fieldsModified = array();
    }
```

---
## Mandango/Extension/Core.php:

```
private function documentSetDocumentDataMethodProcess()  // 632 row
{
.....
    $forzeClean = false;  // Maybe here should specify TRUE ?
.....
        if (isset($field['default'])) {
            $forzeClean = true; // And here should specify FALSE ?
        }
    }
    $fieldsCode = implode("\n", $fieldsCode);
    $forzeClean = $forzeClean ? 'true || ' : '';
.....
```

---

**Comment by pablodip** [comment]
Hmm, I don't know what you see bad here, it's done to behave like that.

When a document has default values and you want to hydrate it (->setDocumentData()), the default values are cleaned because they can not be in the database, and otherwise you'd have the default values instead a null values.
